# Generated by Django 4.1.1 on 2022-10-04 09:18

from django.db import IntegrityError, migrations
from django.conf import settings

import csv

SHOW_TYPE = 1
TITLE = 2
DIRECTOR = 3
CAST = 4
COUNTRIES = 5
DATE_ADDED = 6
RELEASE_YEAR = 7
RATING = 8
DURATION = 9
CATEGORIES = 10
DESCRIPTION = 11

def load_show_data(apps, schema_editor):
    Show = apps.get_model('show', 'Show')
    Person = apps.get_model('show', 'Person')

    with open(settings.DATA_DIR / 'netflix_titles.csv', newline='') as csvfile:
        pokemon_reader = csv.reader(csvfile, delimiter=',')
        next(pokemon_reader)  # skip first row
        for row in pokemon_reader:
            print(f"Show: {row[TITLE][:200]}")
            show = Show.objects.create(
                show_type=row[SHOW_TYPE][:200],
                title=row[TITLE][:200],
                countries=row[COUNTRIES][:200],
                date_added=row[DATE_ADDED][:200],
                release_year=row[RELEASE_YEAR],
                rating=row[RATING][:200],
                duration=row[DURATION][:200],
                categories=row[CATEGORIES][:200],
                description=row[DESCRIPTION][:200],
            )

            directors = row[DIRECTOR].split(",")
            for name in directors:
                if not name:
                    continue

                print(f"Person: {name}")
                person, created = Person.objects.get_or_create(
                    name=name.strip()[:200],
                )

                show.director.add(person)

            cast = row[CAST].split(",")
            for name in cast:
                if not name:
                    continue

                print(f"Person: {name}")
                person, created = Person.objects.get_or_create(
                    name=name.strip()[:200],
                )

                show.cast.add(person)


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_show_data, reverse_code=migrations.RunPython.noop),
    ]
